module.exports={
    checkUser:(req,res,next)=>{
        if(req.session.user){
            console.log("sessionCreated",req.session.user)
            next();
        }
       else{
        res.redirect("/");
       }
    }
}